In [ ]:
import numpy as np

In [ ]:
n1 = 247
p1 = .37

n2 = 308
p2 = .39

population1 = np.random.binomial(1, p1, n1)
population2 = np.random.binomial(1, p2, n2)

In [ ]:
population1

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0])

In [ ]:
population2

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [ ]:
import statsmodels.api as sm
sm.stats.ttest_ind(population1, population2)

(np.float64(-0.6655307090997765),
 np.float64(0.5059885962571871),
 np.float64(553.0))

In [ ]:
data = pd.Series([0.593,0.142,0.329,0.691,0.231,0.793,0.519,0.392,0.418])
p_value = stats.ttest_1samp(data,0.3)[1]
p_value = p_value/2
p_value

np.float64(0.029265164842448826)

In [ ]:
control = pd.Series([91,87,99,77,88,91])
treat = pd.Series([101,110,103,93,99,104])
p_value = stats.ttest_ind(control,treat)[1]
p_value


np.float64(0.006272124350809803)

In [ ]:
from scipy import stats
import pandas as pd
import numpy as np

In [ ]:
# 2 Proportion t-test

n1 = 247
p1 = .36
n2 = 308
p2 = .38

# proportion1 = np.random.binomial(1, p1, n1)
# proportion2 = np.random.binomial(1, p2, n2)

proportion1 = np.random.binomial(1, p1, n1)
proportion2 = np.random.binomial(1, p2, n2)


In [ ]:
proportion1

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0])

In [ ]:
proportion1.mean()


np.float64(0.3724696356275304)

In [ ]:
proportion2.mean()

np.float64(0.39285714285714285)

In [ ]:
import statsmodels.api as sm
sm.stats.ttest_ind(proportion1, proportion2)


(np.float64(-0.49005176043811394),
 np.float64(0.6242916304582325),
 np.float64(553.0))

In [ ]:
result = math.factorial(10)
print(result)  # Output: 120

3628800


In [ ]:
# sample_means = 3.7
# def one_sample_t_test(sample_mean):
#   for sample_mean in sample_means:
#     t_value = (sample_mean-4)/(3/np.sqrt(50))
#     p_value = 2*stats.t.cdf(t_value,49)
#     np.round(p_value,4)
#     return t_value,p_value

np.float64(0.4828)

In [ ]:
sample_means = [3.5,3.6,3.7]
mean_output=[]
t_output = []
for sample_mean in sample_means:
  t_value = (sample_mean-4)/(3/np.sqrt(50))
  t_value = np.round(t_value,4)
  p_value = 2*stats.t.cdf(-abs(t_value),49)
  p_value= np.round(p_value,4)
  mean_output.append(p_value)
  t_output.append(t_value)

print(f"sample means: {sample_means}",f"p_value: {mean_output}", f" t-value: {t_output}", sep='\n')


sample means: [3.5, 3.6, 3.7]
p_value: [np.float64(0.2443), np.float64(0.3504), np.float64(0.4829)]
 t-value: [np.float64(-1.1785), np.float64(-0.9428), np.float64(-0.7071)]


In [ ]:
  t = 3.7-4
t = t*np.sqrt(50)
t = t/3
t

np.float64(-0.7071067811865471)

In [ ]:
glaxo_df=pd.read_csv("/content/glaxo_df.csv")

In [ ]:
glaxo_df

Date      Date.1    Close      gain
0     2010-01-05  2010-01-05  1616.80 -0.005444
1     2010-01-06  2010-01-06  1638.50  0.013422
2     2010-01-07  2010-01-07  1648.70  0.006225
3     2010-01-08  2010-01-08  1639.80 -0.005398
4     2010-01-11  2010-01-11  1629.45 -0.006312
...          ...         ...      ...       ...
1733  2016-12-26  2016-12-26  2723.50 -0.001283
1734  2016-12-27  2016-12-27  2701.75 -0.007986
1735  2016-12-28  2016-12-28  2702.15  0.000148
1736  2016-12-29  2016-12-29  2727.90  0.009529
1737  2016-12-30  2016-12-30  2729.80  0.000697

[1738 rows x 4 columns]

In [ ]:
glaxo_df_ci = stats.norm.interval(0.95,
loc = glaxo_df.gain.mean(),
scale = glaxo_df.gain.std())
print("gain at 95% confidence interval is: ", np.round(glaxo_df_ci,4))

gain at 95% confidence interval is:  [-0.0258  0.0266]


In [ ]:
beml_df=pd.read_csv("/content/beml_df.csv")

In [ ]:
beml_df

Date      Date.1    Close      gain
0     2010-01-05  2010-01-05  1134.60 -0.000881
1     2010-01-06  2010-01-06  1139.60  0.004407
2     2010-01-07  2010-01-07  1144.15  0.003993
3     2010-01-08  2010-01-08  1144.05 -0.000087
4     2010-01-11  2010-01-11  1137.00 -0.006162
...          ...         ...      ...       ...
1733  2016-12-26  2016-12-26   950.25 -0.021924
1734  2016-12-27  2016-12-27   975.70  0.026782
1735  2016-12-28  2016-12-28   974.40 -0.001332
1736  2016-12-29  2016-12-29   986.05  0.011956
1737  2016-12-30  2016-12-30  1000.60  0.014756

[1738 rows x 4 columns]

In [ ]:
beml_df_ci = stats.norm.interval(0.95,
loc = beml_df.gain.mean(),
scale = beml_df.gain.std())
print("gain at 95% confidence interval is: ", np.round(beml_df_ci,4))


gain at 95% confidence interval is:  [-0.0515  0.0521]
